apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-view-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group 
  name: e51dd951-ca6a-433f-9c67-4abff263298e
- apiGroup: rbac.authorization.k8s.io
  kind: Group 
  name: 40384a11-54a1-400a-95b8-a9ea89f48ee3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-view-binding
  namespace: api 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view 
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group 
  name: e51dd951-ca6a-433f-9c67-4abff263298e
- apiGroup: rbac.authorization.k8s.io
  kind: Group 
  name: 40384a11-54a1-400a-95b8-a9ea89f48ee3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-edit-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group 
  name: e51dd951-ca6a-433f-9c67-4abff263298e
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-edit-binding
  namespace: api 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit 
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group 
  name: e51dd951-ca6a-433f-9c67-4abff263298e
- apiGroup: rbac.authorization.k8s.io
  kind: Group 
  name: 40384a11-54a1-400a-95b8-a9ea89f48ee3

