apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tripviewer
  name: tripviewer
  namespace: web
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripviewer
  type: ClusterIP
status:
  loadBalancer: {}
