apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trips
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trips
    spec:
      containers:
      - image: registrynhi6414.azurecr.io/tripviewer/trips
        name: trips
        ports:
        - containerPort: 80  
        
        resources: {}
        
        # https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
        env:
        - name: SQL_USER
          value: "sqladminnHi6414"
        - name: SQL_SERVER
          value: "sqlservernhi6414.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: OPENAPI_DOCS_URI
          value: "http://changeme"
        - name: DEBUG_LOGGING
          value: "false"
    
        # https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
        - name: SQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: sql-password 
                key: SQL_PASSWORD
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password"
                            
status: {}
