apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: userprofile
  name: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: userprofile
    spec:
      containers:
      - image: registrynhi6414.azurecr.io/tripviewer/userprofile
        name: userprofile
        resources: {}
        
        # https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
        env:
        - name: SQL_USER
          value: "sqladminnHi6414"
        - name: SQL_SERVER
          value: "sqlservernhi6414.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"

        # https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#use-a-user-assigned-managed-identity
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
      
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "az-kv-challenge-4"
                            
status: {}
